# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ceb38c68e59fee3af7dea001b72c1a37f090b098ad7a7c8f40919c72b495435ee89c242d703bdc980225b26526b0ab0dbbe3f76952bfb7da163cf254267437

test:
  secret_key_base: 1458524660d7f2cc0cf4c757889a54cf3726de3e18c2d639947dd2e15515c52f7f3568cec9006fb13d8fda313b131adb5d1e346e468317cb6750c22d5644ee6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
